
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-python.python

tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

ports:
  - port: 4567
    visibility: public
    name: Backend
  - port: 3000
    visibility: public
    name: Frontend
  - port: 4317
    visibility: public
    name: X-ray