extensions:
  health_check:
  sigv4auth:
    region: "us-east-1"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
            allowed_origins:
              - https://4567-raveenaj-awsbootcampcru-jen7yud3i3w.ws-us107.gitpod.io
            max_age: 7200

  awsxray:

exporters:
  awsxray:
  otlp:
    endpoint: "api.honeycomb.io"
    tls:
      insecure: true
    headers:
      "x-honeycomb-team": "98cLBTXfZmtxcXOQsXFtmH"
    auth:
      authenticator: sigv4auth

processors:
  batch/traces:

service:
  pipelines:
    traces:
      receivers: [otlp,awsxray]
      processors: [batch/traces]
      exporters: [awsxray, otlp]

  extensions: [health_check, sigv4auth]